package social

func getTopicsArr() []string {
	return []string{
		"Quantum Mechanics",
		"Ancient Civilizations",
		"Continents and Oceans",
		"Shakespeare's Plays",
		"Algebra",
		"Computer Programming",
		"Renaissance Art",
		"Classical Music",
		"Football",
		"Hollywood Classics",
		"Democracy",
		"Ethics",
		"Entrepreneurship",
		"Nutrition",
		"Educational Psychology",
		"Biodiversity",
		"Culinary Arts",
		"Adventure Travel",
		"Fashion History",
		"Cognitive Psychology",
		"World Religions",
		"Microeconomics",
		"Constitutional Law",
		"Social Theory",
		"Cultural Anthropology",
		"The Solar System",
		"Organic Chemistry",
		"Classical Mechanics",
		"Cell Biology",
		"Civil Engineering",
		"Theory of Relativity",
		"World War I",
		"Mountain Ranges",
		"Modernist Literature",
		"Geometry",
		"Cybersecurity",
		"Impressionism",
		"Jazz",
		"Basketball",
		"Independent Films",
		"Authoritarianism",
		"Metaphysics",
		"Marketing",
		"Mental Health",
		"Curriculum Development",
		"Deforestation",
		"World Cuisines",
		"Cultural Tourism",
		"Fashion Design",
		"Developmental Psychology",
		"Religious History",
		"Macroeconomics",
		"Criminal Law",
		"Social Stratification",
		"Physical Anthropology",
		"Stars and Galaxies",
		"Inorganic Chemistry",
		"Electromagnetism",
		"Molecular Biology",
		"Mechanical Engineering",
		"Black Holes",
		"World War II",
		"Rivers of the World",
		"Postcolonial Literature",
		"Calculus",
		"Blockchain Technology",
		"Modern Art",
		"Rock and Roll",
		"Tennis",
		"Film Noir",
		"Political Parties",
		"Epistemology",
		"Finance",
		"Exercise and Fitness",
		"Teaching Methods",
		"Pollution",
		"Food Science",
		"Eco-Tourism",
		"Sustainable Fashion",
		"Social Psychology",
		"Religious Texts",
		"International Economics",
		"International Law",
		"Race and Ethnicity",
		"Archaeology",
		"Cosmology",
		"Physical Chemistry",
		"Thermodynamics",
		"Genetics",
		"Electrical Engineering",
		"DNA and Genetics",
		"The Cold War",
		"Deserts",
		"Greek Mythology",
		"Statistics",
		"Internet of Things",
		"Contemporary Art",
		"Hip Hop",
		"Cricket",
		"Science Fiction Movies",
		"Elections",
		"Logic",
		"Management",
		"Chronic Diseases",
		"E-learning",
		"Sustainable Development",
		"Nutrition",
		"Luxury Travel",
		"Haute Couture",
		"Clinical Psychology",
		"Mythology",
		"Development Economics",
		"Human Rights Law",
		"Gender Studies",
		"Linguistic Anthropology",
		"Exoplanets",
		"Analytical Chemistry",
		"Optics",
		"Ecology",
		"Chemical Engineering",
		"Evolutionary Biology",
		"The Renaissance",
		"Climate Zones",
		"Epic Poetry",
		"Probability",
		"Cloud Computing",
		"Sculpture",
		"Electronic Music",
		"Olympic Games",
		"Horror Movies",
		"International Relations",
		"Political Philosophy",
		"Startups",
		"Public Health",
		"Special Education",
		"Conservation",
		"Food Safety",
		"Backpacking",
		"Street Style",
		"Behavioral Psychology",
		"Spirituality",
		"Behavioral Economics",
		"Corporate Law",
		"Urban Sociology",
		"Ethnography",
		"Astrobiology",
		"Biochemistry",
		"Nuclear Physics",
		"Microbiology",
		"Aerospace Engineering",
		"Climate Change",
		"The Industrial Revolution",
		"Capital Cities",
		"The Novel",
		"Number Theory",
		"Machine Learning",
		"Photography",
		"World Music",
		"Athletics",
		"Documentaries",
		"Political Theory",
		"Existentialism",
		"Corporate Strategy",
		"Healthcare Systems",
		"Higher Education",
		"Ecosystems",
		"Veganism",
		"Travel Photography",
		"Fashion Trends",
		"Neuropsychology",
		"Religious Practices",
		"Economic Policy",
		"Environmental Law",
		"Rural Sociology",
		"Anthropological Theory",
		"Telescopes",
		"Environmental Chemistry",
		"Particle Physics",
		"Zoology",
		"Biomedical Engineering",
		"Renewable Energy",
		"The French Revolution",
		"World Heritage Sites",
		"Literary Criticism",
		"Topology",
		"Data Science",
		"Street Art",
		"Music Theory",
		"Swimming",
		"Animation",
		"Public Policy",
		"Stoicism",
		"International Business",
		"Alternative Medicine",
		"Early Childhood Education",
		"Environmental Policy",
		"Baking",
		"Travel Writing",
		"Fashion Photography",
		"Positive Psychology",
		"Religious Philosophy",
		"Economic History",
		"Intellectual Property Law",
		"Social Movements",
		"Human Evolution",
		"Space Missions",
		"Materials Science",
		"Astrophysics",
		"Botany",
		"Environmental Engineering",
		"Artificial Intelligence",
		"The American Revolution",
		"Population Geography",
		"Famous Authors",
		"Mathematical Logic",
		"Virtual Reality",
		"Digital Art",
		"Famous Composers",
		"Golf",
		"Film Directors",
		"Political Scandals",
		"Philosophy of Mind",
		"E-commerce",
		"Pandemics",
		"Educational Technology",
		"Climate Science",
		"Food History",
		"Travel Safety",
		"Fashion Marketing",
		"Psychotherapy",
		"Religious Art",
		"Labor Economics",
		"Family Law",
		"Cultural Studies",
		"Primatology",
		"Astronomical Phenomena",
		"Chemical Reactions",
		"Fluid Dynamics",
		"Marine Biology",
		"Computer Engineering",
		"Space Exploration",
		"The Roman Empire",
		"Geopolitics",
		"Literary Movements",
		"Applied Mathematics",
		"Augmented Reality",
		"Art History",
		"Music Genres",
		"Winter Sports",
		"Film Festivals",
		"Human Rights",
		"Ancient Philosophy",
		"Business Ethics",
		"Aging",
		"Literacy",
		"Renewable Resources",
		"Food Trends",
		"Travel Technology",
		"Fashion Technology",
		"Psychological Disorders",
		"Religious Conflicts",
		"Financial Markets",
		"Legal Theory",
		"Sociology of Religion",
		"Anthropology of Religion",
		"The Big Bang Theory",
		"Periodic Table",
		"Wave Theory",
		"Evolution",
		"Structural Engineering",
		"Nanotechnology",
		"The Middle Ages",
		"Cartography",
		"Children's Literature",
		"Cryptography",
		"Robotics",
		"Famous Paintings",
		"Music History",
		"Extreme Sports",
		"Movie Awards",
		"Global Governance",
		"Modern Philosophy",
		"Supply Chain Management",
		"Wellness",
		"Global Education",
		"Environmental Ethics",
		"Food Industry",
		"Famous Landmarks",
		"Fashion Icons",
		"Human Behavior",
		"Secularism",
		"Economic Theories",
		"Judicial Systems",
		"Sociology of Education",
		"Medical Anthropology",
		"Dark Matter",
		"Chemical Bonding",
		"Quantum Physics",
		"Biotechnology",
		"Robotics Engineering",
	}
}
