// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"database/sql"
	"time"
)

type Session struct {
	ID                int64
	UserID            int64
	Email             string
	Expiry            time.Time
	Token             sql.NullString
	ActivateCode      sql.NullString
	UserIp            sql.NullString
	Type              string
	PostSuspendExpiry sql.NullTime
	IsExpired         sql.NullBool
}

type User struct {
	ID        int64
	Uuid      string
	Name      string
	Email     sql.NullString
	Salt      string
	ImageUrl  interface{}
	IsDraft   sql.NullBool
	CreatedAt sql.NullTime
}
