// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
	"time"
)

type FunFact struct {
	ID        int64        `json:"id"`
	Topic     string       `json:"topic"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Game struct {
	ID            int64  `json:"id"`
	RoomUuid      string `json:"room_uuid"`
	RoomName      string `json:"room_name"`
	GameContentID int64  `json:"game_content_id"`
}

type GameContent struct {
	ID          int64        `json:"id"`
	Uuid        string       `json:"uuid"`
	MaxRounds   int64        `json:"max_rounds"`
	Category    string       `json:"category"`
	GenContent  string       `json:"gen_content"`
	Language    string       `json:"language"`
	Difficulty  string       `json:"difficulty"`
	ContentJson string       `json:"content_json"`
	UserID      int64        `json:"user_id"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type GameContentAnswer struct {
	ID                 int64  `json:"id"`
	IsCorrect          bool   `json:"is_correct"`
	Content            string `json:"content"`
	GameContentRoundID int64  `json:"game_content_round_id"`
}

type GameContentRound struct {
	ID                 int64  `json:"id"`
	Round              int64  `json:"round"`
	QuestionContent    string `json:"question_content"`
	CorrectAnswerIndex int64  `json:"correct_answer_index"`
	GameContentID      int64  `json:"game_content_id"`
}

type GameRoundAction struct {
	ID        int64        `json:"id"`
	AnswerID  int64        `json:"answer_id"`
	Points    int64        `json:"points"`
	GameID    int64        `json:"game_id"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type GameUser struct {
	ID         int64        `json:"id"`
	UserID     int64        `json:"user_id"`
	Level      int64        `json:"level"`
	Exp        float64      `json:"exp"`
	GamesWins  int64        `json:"games_wins"`
	RoundWins  int64        `json:"round_wins"`
	Percentage float64      `json:"percentage"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type GameWinner struct {
	ID        int64        `json:"id"`
	Points    int64        `json:"points"`
	GameID    int64        `json:"game_id"`
	UserID    int64        `json:"user_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Session struct {
	ID                int64        `json:"id"`
	UserID            int64        `json:"user_id"`
	Email             string       `json:"email"`
	Expiry            time.Time    `json:"expiry"`
	Token             string       `json:"token"`
	ActivateCode      string       `json:"activate_code"`
	RefreshToken      string       `json:"refresh_token"`
	UserIp            string       `json:"user_ip"`
	Type              string       `json:"type"`
	PostSuspendExpiry sql.NullTime `json:"post_suspend_expiry"`
	IsExpired         sql.NullBool `json:"is_expired"`
}

type User struct {
	ID        int64          `json:"id"`
	Uuid      string         `json:"uuid"`
	Name      string         `json:"name"`
	Email     sql.NullString `json:"email"`
	Salt      string         `json:"salt"`
	ImageUrl  string         `json:"image_url"`
	IsDraft   bool           `json:"is_draft"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
